# Generated by Django 3.2.3 on 2021-05-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='image',
            name='image_description',
            field=models.CharField(default='DEFAULT VALUE', max_length=500),
        ),
    ]
